### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dmfs** [codeka/carrot#1]
Would you accept a PR which replaces some dependencies with Android compliant code? We're considering to use this library in an Android project (OpenTasks), but some dependencies are not available on current and older platform versions. At present the only problematic classes appear to be [java.nio.file.Paths](https://developer.android.com/reference/java/nio/file/Paths.html) and [java.nio.file.Path](https://developer.android.com/reference/java/nio/file/Path.html), which are not available on Android so far.
Also we'd like to replace lambdas, because support for this in Android didn't fully arrive yet.
Ideally we don't have to maintain our own fork but can use the upstream build, hence the question.

**Comment by codeka** [comment]
Yes, I would be fine with swapping out java.nio.file.Paths for an Android-compatible implementation.

I'm not sure how extensively I've used lambdas, I don't think it's that much? If it's only a few places I'd be find with removing those as well.

**Comment by codeka** [comment]
I just pushed a quick update which should do the trick, there was only one lambda in the main library (there's a couple in the tests, but I figure that's OK since you're not running that on Android). Let me know if the code works, I'll push this to maven when I get a chance.

**Comment by dmfs** [comment]
@codeka thanks a lot. We'll give it a try.
