### ISSUE TITLE
boolean operator precedence 

### ISSUE THREAD

**Issue by dmfs** [codeka/carrot#15]
The boolean operators `&&` and `||` don't appear to follow the common precedence rules. In particular the last one of these test fails:

```java
Map<String, Object> context = ImmutableMap.of("true", (Object) true, "false", false);

// tests that pass:
assertThat(render("{{ true && true }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ true || false }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ false || true }}", new MapBindings(context))).isEqualTo("true");
assertThat(render("{{ (false && false) || true }}", new MapBindings(context))).isEqualTo("true");

// failing test:
assertThat(render("{{ false && false || true }}", new MapBindings(context))).isEqualTo("true");
```

The common order of boolean operators is "and" before "or", see https://en.wikipedia.org/wiki/Logical_connective#Order_of_precedence

so `false && false || true` should be evaluated like `(false && false) || true` which is `true`.

**Comment by dmfs** [comment]
The problem lies in the grammar on top of `StatementParser`. While it would produce correct expressions, it implies the wrong operator precedence.

Here is a grammar based on the precedence in https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html:

```
value =
    variable
    | number
    | literal
    | "(" expression ")"

unary-term = ["!"] value

multiplicative-term = unnary-term [("*" | "/") unary-term]

additive-term = multiplicative-term [("+" | "-") multiplicative-term]

relational-term = additive-term [("<" | "<=" | ">" | ">=") additive-term]

equality-term = relational-term [("==" | "!=") relational-term]

and-term = equality-term ["&&" equality-term]

or-term = and-term ["||" and-term]

expression = or-term
```

It shows that the unary `!` operator is closest to the value and evaluated first, while the `||` operator has the lowest precedence and is evaluated last.

**Comment by codeka** [comment]
Oh yeah, you're right. I think I've actually got it pretty much all backwards :\ OK, I think this is actually not that hard to fix...

**Comment by dmfs** [comment]
I'll take care of this.
