### ISSUE TITLE
Use a builder to construct an immutable CarrotEngine (including config, global bindings, etc)

### ISSUE THREAD

**Issue by dmfs** [codeka/carrot#27]
Just out of curiosity, what's the point of mutable global Bindings?
Why would I want to add something to the global bindings after creating a `CarrotEngine`? I can always just update the `Bindings` (e.g. with `Composite` bindings) which I pass to `process` if I need additional bindings.
IMO, it's preferable to preserve immutability whenever possible.

**Comment by dmfs** [comment]
Actually I was planning to propose the removal of `CarrotEngine.getGlobalBindings()`. I don't see how this would be useful outside of the context of a template.

**Comment by codeka** [comment]
I was mostly making it the same as `getConfig()` which is mutable as well. But now that I think about it, it's probably better to use a builder pattern for constructing CarrotEngine and then making the whole thing immutable.

The way it works now is just how it worked when I forked it from the original project...

**Comment by codeka** [comment]
Fixed in e628dc3281b73a6f95593f1f31e85df2b5d2a885.
