### ISSUE TITLE
} disapear if alone in a line

### ISSUE THREAD

**Issue by criocere** [codeka/carrot#30]
Hello,

I have this bash code in an include

```
installProduct() {
	mkdir -p {{aa}}
	tar xvf {{bb}} --dir {{cc}}
}
```

and in my main

`{% include "myfile.inc.sh" %}`

and the result after calling carrot is

```
installProduct() {
	mkdir -p AA
	tar xvf BB --dir CC
```

The line containing the } without space after disapears!
I found a workaround by adding a space after the }

**Comment by codeka** [comment]
Good catch, thanks!
