### ISSUE TITLE
Process String input instead of File

### ISSUE THREAD

**Issue by balintbarna** [codeka/carrot#31]

**Comment by codeka** [comment]
You can do string processing using something like this:

    public String processString(String tmpl, Bindings bindings) {
      CarrotEngine engine = new CarrotEngine(
          new Configuration.Builder()
              .setResourceLocator(
                  new MemoryResourceLocator.Builder().add("index.html", template))
          .build());
      return engine.process("index.html", bindings);
    }

**Comment by balintbarna** [comment]
Thank you for the answer :)
Is there a way to insert files' contents from the resources using the include tag if you do this?
