### ISSUE TITLE
Issue referencing Carrot from MVN Repository

### ISSUE THREAD

**Issue by MatiasDwek** [codeka/carrot#34]
I can't get Carrot version 2.4.2 to compile with Gradle by adding the dependency `compile 'au.com.codeka:carrot:2.4.2`.

In addition, when I go to the [MVN Repository site](https://mvnrepository.com/artifact/au.com.codeka/carrot/2.4.2), there doesn't seem to be any .jar file, whereas I do find all the compiled files for [other versions](https://mvnrepository.com/artifact/au.com.codeka/carrot/2.4.1). Am I missing something or are the files missing at MVN Repository?

Thank you in advance.

**Comment by codeka** [comment]
I just published a new one with the same version number that should work. I'm not sure if re-uploading with the same version number will actually work (takes a while to show up in mvn-repository) so if not I might bump the version number and try again tonight (in the meantime, 2.4.1 should work).

Just leaving this issue open until I confirm.

**Comment by codeka** [comment]
Ok, seems to have propagated: http://central.maven.org/maven2/au/com/codeka/carrot/2.4.2

Let me know if it's not working still.

**Comment by MatiasDwek** [comment]
I can also see the propagated changes. Thanks for the quick fix.
