### ISSUE TITLE
Is carrot still alive?

### ISSUE THREAD

**Issue by criocere** [codeka/carrot#36]
I use carrot and like its capabilities but I wonder if this project is still alive as I see no modification, no fix and no enhancement since a while?

**Comment by codeka** [comment]
Yes, I still use it in my own projects, I just haven't had any recent bug reports or feature requests to do, so it's been working nicely for me :)

**Comment by criocere** [comment]
Thanks for you reply :o)
I use also a lot of carrot and I will have requests soon! For example how to escape java operator (+, -, ^) in a variable name? I will open this request.
My issue about concatenation of strings is still open, can you have a look?
