### ISSUE TITLE
Support for include tag

### ISSUE THREAD

**Issue by dmfs** [codeka/carrot#7]
Is there any support for an `include` tag like in [Jinja](http://jinja.pocoo.org/docs/2.9/templates/#include)?
I couldn't find any. Is there any other way to achieve the same (other than a custom tag)?

**Comment by codeka** [comment]
I considered it, but never bothered adding one. `{% extends %}` is kind of like include, only more powerful. It shouldn't be hard to add an include tag though.

**Comment by dmfs** [comment]
Our use case is to share common elements between different templates. Like a footer block which is always the same for multiple (base) templates. Or a list element which is used in various listings.

I think these can not be solved with `extends`.
